#########################################################################################################
# 001-HEADER
#########################################################################################################
# menu
menu:
    home: /
    archive: /archives
    categories: /categories
    tags: /tags
    about: /about
    #gallery: /gallery

# favicon & logo
favicon: https://cdn.jsdelivr.net/gh/nekoremy/cdn@master/favicon-2.ico
logo: https://cdn.jsdelivr.net/gh/nekoremy/cdn@master/logo.webp

# background_image
# mask_alpha: 0 ~ 1
# mode: normal | random_you | random_other
# normal_url: /img/header-bg.jpg
# random_you_url: https://sariay.github.io/Random-img/
# random_other_url: https://source.unsplash.com/collection/954550/1920x1080 | https://api.berryapi.net/?service=App.Bing.Images&day=-0
mask_alpha: 0.4
background_image:
    mode: normal
    normal_url: https://api.addesp.com/image/wallpaper/acg
    random_you_max: 110
    random_you_url: https://sariay.github.io/Random-img/
    random_other_url: https://api.berryapi.net/?service=App.Bing.Images&day=-0

# motto 
# source: local | hitokoto
motto:
	enable: false
	source: local
timejs:
  enable: true  

#########################################################################################################
# 002-PROLOADER
#########################################################################################################
# animation: spinner | transition | cyclic
preloader:
    enable: true
    animation: cyclic

#########################################################################################################
# 003-INDEX
#########################################################################################################
# index-style: pure | cart
index_style: cart

# index_cart_cover
cover: /img/cart_cover.jpg
lazy_image: https://cdn.jsdelivr.net/gh/nekoremy/cdn@master/lazy.gif

#########################################################################################################
# 004-POST
#########################################################################################################
# post_relate
relate:
    enable: true
    posts_limit: 1
    posts_excerpt: 120

# post_comment
comment:
    enable: true

gitalk:
    enable: true
    clientID: '8ac4005a0975a8a0040f' 
    clientSecret: 'bf3d321a2aa25e5f00cf6d88d7574c4aa4b7db7a' 
    repo: nekoremy.github.io
    owner: nekoremy
    admin: nekoremy
    distractionFreeMode: true
    #去除 more、index.html、?query=123等格式尾部 
    hrefTrimend: '#.*$,\\?.*$,index.html$' 
    
valine: 
    enable: false
    appid: ''
    appkey: ''
    placeholder: no any!
    
livere: 
    enable: false
    livere_uid: 'sdd'
    
# post_count
leancloud_count:
    enable: false
    appid: ''
    appkey: ''
    serverURLs: 'http'
    like_post:
        enable: true
    visit_post:
        enable: false
    topN_post: 
        enable: true 
        limit: 10

busuanzi_count:
    enable: false

baidu_analytics:
    enable: false
    id: 

cnzz_analytics:
    enable: false
    id:

google_analytics:
    enable: false
    id: G-85DDXT8DCP

tencent_analytics:
    enable: false
    id:

# post_toc
post_toc:
    enable: true
    katelog: true
    
# post_mathJax
mathjax:
  enable: true
  
# post_code
# hlight_theme: normal | night | night blue | night bright | night eighties
highlight_theme: night
code_copy:
    enable: true

# post_excerpt for index page
excerpt_cart: 80
excerpt_pure: 300   
excerpt_link: false

# post_share
share:
    enable: true
# https://www.addthis.com/
# 注意浏览器的内容拦截插件
addThis:
    enable: true
    id: ra-5effa74039abca35
# http://share.baidu.com/code
baiduShare: 
    enable: false
    style: button # you can add slide style!
# https://www.sharethis.com/onboarding-cms/    
shareThis:
    enable: false
    id: 5c-xxx
# https://github.com/overtrue/share.js
socialShare:
    enable: true

#########################################################################################################
# 005-FOOTER
#########################################################################################################
# social links
# Check the icon in the page of Icomoon
social:
	email:
        url: mailto:neko.remy@outlook.com
        icon: <span class="icon-envelope"></span>  
	github:
        url: http://github.com/nekoremy
        icon: <span class="icon-github"></span>   
	rss: 
        url: /atom.xml
        icon: <span class="icon-rss"></span>

# copyright  
since: 2020
author: Remy

#########################################################################################################
# 006-GALLERY PAGE
#########################################################################################################
# gallery page
# gallery_format: natural | square
gallery_format: natural
# one time to load 4 rows or other count, 0 to load img automatically when scrolling.(0,1,2,3,4,5,6......)
gallery_limit: 0
# data url
gallery_data: plugin/gallerypage/data.json

#########################################################################################################
# 007-LOCAL SEARCH
#########################################################################################################
# Local search
# Dependencies: https://github.com/flashlab/hexo-generator-search
local_search:
    enable: true
    # if auto, trigger search by changing input
    # if manual, trigger search by pressing enter key or search button
    trigger: auto
    # show top n results per article, show all results by setting to -1
    top_n_per_article: 2

#########################################################################################################
# 008-OTHERS
#########################################################################################################
# when click, emerge heart
love:
    enable: false

# back to top
totop:
    enable: true
